[2025-04-19T15:09:17.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-19T15:09:18.060+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_etl_pipeline_mart.dbt_marts_business scheduled__2025-04-19T15:08:46.193728+00:00 [queued]>
[2025-04-19T15:09:18.074+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_etl_pipeline_mart.dbt_marts_business scheduled__2025-04-19T15:08:46.193728+00:00 [queued]>
[2025-04-19T15:09:18.076+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-19T15:09:18.090+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_marts_business> on 2025-04-19 15:08:46.193728+00:00
[2025-04-19T15:09:18.097+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=903) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-19T15:09:18.098+0000] {standard_task_runner.py:72} INFO - Started process 904 to run task
[2025-04-19T15:09:18.098+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_etl_pipeline_mart', 'dbt_marts_business', 'scheduled__2025-04-19T15:08:46.193728+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/dbt_marts.py', '--cfg-path', '/tmp/tmpjdi_7qv8']
[2025-04-19T15:09:18.100+0000] {standard_task_runner.py:105} INFO - Job 198: Subtask dbt_marts_business
[2025-04-19T15:09:18.272+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_etl_pipeline_mart.dbt_marts_business scheduled__2025-04-19T15:08:46.193728+00:00 [running]> on host 27536697ee14
[2025-04-19T15:09:18.484+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='dbt_etl_pipeline_mart' AIRFLOW_CTX_TASK_ID='dbt_marts_business' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T15:08:46.193728+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-19T15:08:46.193728+00:00'
[2025-04-19T15:09:18.485+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-19T15:09:18.496+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-19T15:09:18.497+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        export PATH=/home/airflow/.local/bin:$PATH\n        cd /opt/airflow/commerce_dbt\n        dbt run --select marts.business --profiles-dir .\n        ']
[2025-04-19T15:09:18.504+0000] {subprocess.py:99} INFO - Output:
[2025-04-19T15:09:20.677+0000] {subprocess.py:106} INFO - [0m15:09:20  Running with dbt=1.7.0
[2025-04-19T15:09:20.944+0000] {subprocess.py:106} INFO - [0m15:09:20  Registered adapter: postgres=1.7.0
[2025-04-19T15:09:21.458+0000] {subprocess.py:106} INFO - [0m15:09:21  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-19T15:09:21.458+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-04-19T15:09:21.459+0000] {subprocess.py:106} INFO - - seeds.initial_dataset
[2025-04-19T15:09:21.509+0000] {subprocess.py:106} INFO - [0m15:09:21  Found 13 models, 1 snapshot, 6 seeds, 43 tests, 6 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-04-19T15:09:21.512+0000] {subprocess.py:106} INFO - [0m15:09:21
[2025-04-19T15:09:21.926+0000] {subprocess.py:106} INFO - [0m15:09:21  Concurrency: 4 threads (target='dev')
[2025-04-19T15:09:21.927+0000] {subprocess.py:106} INFO - [0m15:09:21
[2025-04-19T15:09:21.939+0000] {subprocess.py:106} INFO - [0m15:09:21  1 of 2 START sql table model commerce_business.customer_orders ................. [RUN]
[2025-04-19T15:09:21.940+0000] {subprocess.py:106} INFO - [0m15:09:21  2 of 2 START sql table model commerce_business.product_sales ................... [RUN]
[2025-04-19T15:09:22.193+0000] {subprocess.py:106} INFO - [0m15:09:22  2 of 2 OK created sql table model commerce_business.product_sales .............. [[32mSELECT 17[0m in 0.25s]
[2025-04-19T15:09:22.194+0000] {subprocess.py:106} INFO - [0m15:09:22  1 of 2 OK created sql table model commerce_business.customer_orders ............ [[32mSELECT 1000[0m in 0.25s]
[2025-04-19T15:09:22.248+0000] {subprocess.py:106} INFO - [0m15:09:22
[2025-04-19T15:09:22.250+0000] {subprocess.py:106} INFO - [0m15:09:22  Finished running 2 table models in 0 hours 0 minutes and 0.74 seconds (0.74s).
[2025-04-19T15:09:22.282+0000] {subprocess.py:106} INFO - [0m15:09:22
[2025-04-19T15:09:22.283+0000] {subprocess.py:106} INFO - [0m15:09:22  [32mCompleted successfully[0m
[2025-04-19T15:09:22.284+0000] {subprocess.py:106} INFO - [0m15:09:22
[2025-04-19T15:09:22.284+0000] {subprocess.py:106} INFO - [0m15:09:22  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2025-04-19T15:09:23.445+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-19T15:09:23.599+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-19T15:09:23.600+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_etl_pipeline_mart, task_id=dbt_marts_business, run_id=scheduled__2025-04-19T15:08:46.193728+00:00, execution_date=20250419T150846, start_date=20250419T150918, end_date=20250419T150923
[2025-04-19T15:09:23.777+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-19T15:09:23.840+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-19T15:09:23.842+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
