[2025-04-18T13:15:13.221+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T13:15:13.278+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_etl_pipeline_mart.dbt_marts_core manual__2025-04-18T13:13:36.481334+00:00 [queued]>
[2025-04-18T13:15:13.291+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_etl_pipeline_mart.dbt_marts_core manual__2025-04-18T13:13:36.481334+00:00 [queued]>
[2025-04-18T13:15:13.293+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-18T13:15:13.309+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_marts_core> on 2025-04-18 13:13:36.481334+00:00
[2025-04-18T13:15:13.317+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=485) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T13:15:13.315+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_etl_pipeline_mart', 'dbt_marts_core', 'manual__2025-04-18T13:13:36.481334+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/dbt_marts.py', '--cfg-path', '/tmp/tmpy5fhtnqx']
[2025-04-18T13:15:13.318+0000] {standard_task_runner.py:72} INFO - Started process 486 to run task
[2025-04-18T13:15:13.318+0000] {standard_task_runner.py:105} INFO - Job 129: Subtask dbt_marts_core
[2025-04-18T13:15:13.505+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_etl_pipeline_mart.dbt_marts_core manual__2025-04-18T13:13:36.481334+00:00 [running]> on host 9c8f13362ff5
[2025-04-18T13:15:13.722+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='dbt_etl_pipeline_mart' AIRFLOW_CTX_TASK_ID='dbt_marts_core' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T13:13:36.481334+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T13:13:36.481334+00:00'
[2025-04-18T13:15:13.723+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T13:15:13.741+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-18T13:15:13.742+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        export PATH=/home/airflow/.local/bin:$PATH\n        cd /opt/airflow/commerce_dbt\n        dbt run --select marts.core --profiles-dir .\n        ']
[2025-04-18T13:15:13.748+0000] {subprocess.py:99} INFO - Output:
[2025-04-18T13:15:16.591+0000] {subprocess.py:106} INFO - [0m13:15:16  Running with dbt=1.7.0
[2025-04-18T13:15:16.846+0000] {subprocess.py:106} INFO - [0m13:15:16  Registered adapter: postgres=1.7.0
[2025-04-18T13:15:17.599+0000] {subprocess.py:106} INFO - [0m13:15:17  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-18T13:15:17.600+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-04-18T13:15:17.600+0000] {subprocess.py:106} INFO - - seeds.initial_dataset
[2025-04-18T13:15:17.640+0000] {subprocess.py:106} INFO - [0m13:15:17  Found 13 models, 1 snapshot, 6 seeds, 43 tests, 6 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-04-18T13:15:17.643+0000] {subprocess.py:106} INFO - [0m13:15:17
[2025-04-18T13:15:17.968+0000] {subprocess.py:106} INFO - [0m13:15:17  Concurrency: 4 threads (target='dev')
[2025-04-18T13:15:17.969+0000] {subprocess.py:106} INFO - [0m13:15:17
[2025-04-18T13:15:17.979+0000] {subprocess.py:106} INFO - [0m13:15:17  1 of 5 START sql table model commerce_core.dim_customers ....................... [RUN]
[2025-04-18T13:15:17.980+0000] {subprocess.py:106} INFO - [0m13:15:17  2 of 5 START sql table model commerce_core.dim_products ........................ [RUN]
[2025-04-18T13:15:17.980+0000] {subprocess.py:106} INFO - [0m13:15:17  3 of 5 START sql table model commerce_core.dim_stores .......................... [RUN]
[2025-04-18T13:15:18.215+0000] {subprocess.py:106} INFO - [0m13:15:18  2 of 5 OK created sql table model commerce_core.dim_products ................... [[32mSELECT 17[0m in 0.23s]
[2025-04-18T13:15:18.217+0000] {subprocess.py:106} INFO - [0m13:15:18  3 of 5 OK created sql table model commerce_core.dim_stores ..................... [[32mSELECT 5[0m in 0.23s]
[2025-04-18T13:15:18.224+0000] {subprocess.py:106} INFO - [0m13:15:18  4 of 5 START sql table model commerce_core.fct_orders .......................... [RUN]
[2025-04-18T13:15:18.224+0000] {subprocess.py:106} INFO - [0m13:15:18  5 of 5 START sql table model commerce_core.ml_analytics ........................ [RUN]
[2025-04-18T13:15:18.311+0000] {subprocess.py:106} INFO - [0m13:15:18  1 of 5 OK created sql table model commerce_core.dim_customers .................. [[32mSELECT 1000[0m in 0.33s]
[2025-04-18T13:15:18.428+0000] {subprocess.py:106} INFO - [0m13:15:18  4 of 5 OK created sql table model commerce_core.fct_orders ..................... [[32mSELECT 10000[0m in 0.20s]
[2025-04-18T13:15:18.433+0000] {subprocess.py:106} INFO - [0m13:15:18  5 of 5 OK created sql table model commerce_core.ml_analytics ................... [[32mSELECT 10000[0m in 0.20s]
[2025-04-18T13:15:18.493+0000] {subprocess.py:106} INFO - [0m13:15:18
[2025-04-18T13:15:18.494+0000] {subprocess.py:106} INFO - [0m13:15:18  Finished running 5 table models in 0 hours 0 minutes and 0.85 seconds (0.85s).
[2025-04-18T13:15:18.565+0000] {subprocess.py:106} INFO - [0m13:15:18
[2025-04-18T13:15:18.566+0000] {subprocess.py:106} INFO - [0m13:15:18  [32mCompleted successfully[0m
[2025-04-18T13:15:18.567+0000] {subprocess.py:106} INFO - [0m13:15:18
[2025-04-18T13:15:18.568+0000] {subprocess.py:106} INFO - [0m13:15:18  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 TOTAL=5
[2025-04-18T13:15:19.626+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-18T13:15:19.745+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T13:15:19.746+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_etl_pipeline_mart, task_id=dbt_marts_core, run_id=manual__2025-04-18T13:13:36.481334+00:00, execution_date=20250418T131336, start_date=20250418T131513, end_date=20250418T131519
[2025-04-18T13:15:19.904+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T13:15:19.978+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-18T13:15:19.981+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
