[2025-04-19T16:02:39.760+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-19T16:02:39.842+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_orders.store_to_sql_order_items manual__2025-04-19T16:02:35.274939+00:00 [queued]>
[2025-04-19T16:02:39.862+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_orders.store_to_sql_order_items manual__2025-04-19T16:02:35.274939+00:00 [queued]>
[2025-04-19T16:02:39.863+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-19T16:02:39.880+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): store_to_sql_order_items> on 2025-04-19 16:02:35.274939+00:00
[2025-04-19T16:02:39.890+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6113) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-19T16:02:39.891+0000] {standard_task_runner.py:72} INFO - Started process 6114 to run task
[2025-04-19T16:02:39.890+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_orders', 'store_to_sql_order_items', 'manual__2025-04-19T16:02:35.274939+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_orders.py', '--cfg-path', '/tmp/tmpfuxql_aw']
[2025-04-19T16:02:39.893+0000] {standard_task_runner.py:105} INFO - Job 261: Subtask store_to_sql_order_items
[2025-04-19T16:02:40.230+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_orders.store_to_sql_order_items manual__2025-04-19T16:02:35.274939+00:00 [running]> on host 27536697ee14
[2025-04-19T16:02:40.538+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_orders' AIRFLOW_CTX_TASK_ID='store_to_sql_order_items' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T16:02:35.274939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-19T16:02:35.274939+00:00'
[2025-04-19T16:02:40.540+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-19T16:02:42.185+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:02:47.311+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:02:52.395+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:02:57.488+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:02.554+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:07.669+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:12.866+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:17.958+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:23.021+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:28.115+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:33.183+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:38.269+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:43.342+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:48.400+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:53.619+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:03:58.711+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:04:03.771+0000] {trigger_dagrun.py:257} INFO - Waiting for load_new_order_items on 2025-04-19 16:02:35.274939+00:00 to become allowed state ['success'] ...
[2025-04-19T16:04:08.268+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2025-04-19T16:04:08.268+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-19T16:04:08.270+0000] {process_utils.py:132} INFO - Sending 15 to group 6114. PIDs of all processes in the group: [6114]
[2025-04-19T16:04:08.270+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 6114
[2025-04-19T16:04:08.271+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-19T16:04:08.273+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/scheduler_command.py", line 56, in scheduler
    run_command_with_daemon_option(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/scheduler_command.py", line 59, in <lambda>
    callback=lambda: _run_scheduler_job(args),
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/scheduler_command.py", line 47, in _run_scheduler_job
    run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/scheduler_job_runner.py", line 990, in _execute
    executor.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/executors/local_executor.py", line 392, in start
    self.impl.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/executors/local_executor.py", line 330, in start
    worker.start()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/executors/local_executor.py", line 80, in run
    return super().run()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/traces/tracer.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/executors/local_executor.py", line 211, in do_work
    self.execute_work(key=key, command=command)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/traces/tracer.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/executors/local_executor.py", line 100, in execute_work
    state = self._execute_work_in_fork(command)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/traces/tracer.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/executors/local_executor.py", line 142, in _execute_work_in_fork
    args.func(args)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 263, in execute
    time.sleep(self.poke_interval)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-04-19T16:04:08.444+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-19T16:04:08.484+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6114, status='terminated', exitcode=0, started='16:02:39') (6114) terminated with exit code 0
