[2025-04-18T00:51:25.777+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T00:51:25.849+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_order_items.load_new_order_items manual__2025-04-18T00:51:24.482378+00:00 [queued]>
[2025-04-18T00:51:25.863+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_order_items.load_new_order_items manual__2025-04-18T00:51:24.482378+00:00 [queued]>
[2025-04-18T00:51:25.876+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-18T00:51:25.903+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_new_order_items> on 2025-04-18 00:51:24.482378+00:00
[2025-04-18T00:51:25.919+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2273) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T00:51:25.915+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_order_items', 'load_new_order_items', 'manual__2025-04-18T00:51:24.482378+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_order_items.py', '--cfg-path', '/tmp/tmpflyowfcg']
[2025-04-18T00:51:25.920+0000] {standard_task_runner.py:72} INFO - Started process 2274 to run task
[2025-04-18T00:51:25.921+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask load_new_order_items
[2025-04-18T00:51:26.270+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_order_items.load_new_order_items manual__2025-04-18T00:51:24.482378+00:00 [running]> on host f693ba064550
[2025-04-18T00:51:26.662+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_order_items' AIRFLOW_CTX_TASK_ID='load_new_order_items' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T00:51:24.482378+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T00:51:24.482378+00:00'
[2025-04-18T00:51:26.663+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T00:51:26.851+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-18T00:51:26.914+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T00:51:26.914+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=load_new_order_items, task_id=load_new_order_items, run_id=manual__2025-04-18T00:51:24.482378+00:00, execution_date=20250418T005124, start_date=20250418T005125, end_date=20250418T005126
[2025-04-18T00:51:27.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T00:51:27.260+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T00:51:27.264+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
